version: "3.7"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/geolocation/src
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "3001:8080"
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: postgres
volumes:
  postgres:
